#!/bin/bash

set -euo pipefail

echo "=> Running post_push hook"

VPP_VERSION=$(docker run --rm $IMAGE_NAME cat /vpp/version | sed -e 's/~/./g')

echo "Tagging image $IMAGE_NAME with additional tag $VPP_VERSION"

docker tag $IMAGE_NAME $DOCKER_REPO:$VPP_VERSION
docker push $DOCKER_REPO:$VPP_VERSION
